<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Be.StoryVerse.Cache</RootNamespace>
    <AssemblyName>Be.StoryVerse.Cache</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Be.StoryVerse.Core\Be.StoryVerse.Core.csproj" />
    <ProjectReference Include="..\Be.StoryVerse.Shared\Be.StoryVerse.Shared.csproj" />
  </ItemGroup>

</Project>
