<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Be.StoryVerse.Shared</RootNamespace>
    <AssemblyName>Be.StoryVerse.Shared</AssemblyName>
  </PropertyGroup>

</Project>
