<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Authentication.Application</RootNamespace>
    <AssemblyName>Authentication.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authentication.Domain\Authentication.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Be.StoryVerse.Cache\Be.StoryVerse.Cache.csproj" />
    <ProjectReference Include="..\..\..\Shared\Be.StoryVerse.Core\Be.StoryVerse.Core.csproj" />
  </ItemGroup>

</Project>
