<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Authentication.Domain</RootNamespace>
    <AssemblyName>Authentication.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Be.StoryVerse.Core\Be.StoryVerse.Core.csproj" />
    <ProjectReference Include="..\..\..\Shared\Be.StoryVerse.EventBus\Be.StoryVerse.EventBus.csproj" />
    <ProjectReference Include="..\..\..\Shared\Be.StoryVerse.Shared\Be.StoryVerse.Shared.csproj" />
  </ItemGroup>

</Project>
